dist: trusty
sudo: required

language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS docman_test;'

install:
  - npm i -g npm@latest
  - npm install

script:
  - npm run coveralls

addons:
    code_climate:
        repo_token: 83d113df31a90a1f96c46cc9d6b8baa73c5f4ff742c129980a2ea74c87d00025