sudo: false

language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

services:
  - mysql

install:
  - npm i -g npm@latest
  - npm install

script:
  - npm test

after_success:
  - npm run coveralls